development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://tiqgfpusgsfegv:a8ef202a81c9753143858a8f0f18f61a722a699413efbfbca83f40f9bfdda324@ec2-54-235-88-58.compute-1.amazonaws.com:5432/d1a04u1mh0jida
  channel_prefix: My_App_production
